package org.groundzero.mesh.llm

import org.groundzero.mesh.gateway.RadminLlmSummarizer
import org.groundzero.mesh.gateway.RankedIncident
import org.groundzero.mesh.gateway.TacticalSummarizer
import org.groundzero.mesh.gateway.TwinSnapshot

/**
 * The real model behind the seam `RadminLlmSummarizer` was standing in for.
 *
 * `TacticalSummarizer`'s doc has always said a model dropped in here "cannot misbehave in
 * the one way that would matter, no matter what it generates" — it is handed an
 * already-ranked board and can only return text. This is that drop-in, and the guarantee is
 * unchanged: nothing in this class has a path back to the ranker.
 *
 * On any failure it delegates to [RadminLlmSummarizer], the deterministic stand-in, so a
 * caller holding this type still gets the same sentences a dispatcher would write when
 * there is no model, no corpus and no server.
 *
 * The richer entry point is [LlmAdvisor.advise], which also answers a responder's typed
 * question and reports whether a model actually answered. This narrow one exists so an
 * existing `TacticalSummarizer` call site gains the model by changing one constructor.
 */
class LlmTacticalSummarizer(
    private val advisor: LlmAdvisor = LlmAdvisor(),
    private val deterministic: TacticalSummarizer = RadminLlmSummarizer(),
    private val nowMs: () -> Long = System::currentTimeMillis,
) : TacticalSummarizer {

    override fun summarise(board: List<RankedIncident>, snapshot: TwinSnapshot): String {
        val view = BoardView.of(board, snapshot, nowMs())
        val advisory = advisor.advise(view, question = null)
        if (!advisory.grounded) return deterministic.summarise(board, snapshot)
        val citations = advisory.sources.takeIf { it.isNotEmpty() }
            ?.joinToString("; ", prefix = "\nSources: ")
            .orEmpty()
        return advisory.text + citations +
            "\nAdvisory only — generated by ${advisory.model}; the ranking above is unchanged."
    }
}
