#!/usr/bin/env python3
"""Place and move virtual Android devices in netsim's shared radio medium.

netsim is the radio simulator that ships inside the Android emulator
(`$ANDROID_HOME/emulator/netsimd`). Every emulator launched on one host attaches
its virtual Bluetooth/BLE/Wi-Fi/UWB controllers to the *same* netsimd process, so
the emulators form one radio scene rather than N isolated islands. Each device in
that scene carries a 3D `Position` (see `proto/model.proto`), and netsim decides
what reaches whom from those coordinates.

That is the whole trick this project needs: three phones, three rooms and a
person willing to be trapped, replaced by three emulators and a coordinate.

    netsimctl.py list                      what netsim currently sees
    netsimctl.py place emulator-5554 0 0 0
    netsimctl.py walk emulator-5554 0 0 --to 120 0 --seconds 30
    netsimctl.py scenario scenarios/collapse.json
    netsimctl.py reset

Units are netsim scene units. `--metres-per-unit` on `scenario` documents what a
unit means for a given run; nothing here converts, it only records the intent in
the printed log so a run is reproducible.

Requires stubs generated by `setup.sh` (grpcio + grpcio-tools).
"""

from __future__ import annotations

import argparse
import configparser
import json
import os
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
GEN = HERE / "gen"
sys.path.insert(0, str(GEN))

# Re-exec inside setup.sh's venv, so `./netsimctl.py` works whatever python3
# happens to be first on PATH. Compare sys.prefix, not the interpreter path:
# venv/bin/python is a symlink to the base interpreter, so resolving it would
# make every python look like the venv's.
VENV = HERE / "venv"
if (VENV / "bin" / "python").exists() and Path(sys.prefix) != VENV:
    python = str(VENV / "bin" / "python")
    os.execv(python, [python, str(Path(__file__).resolve()), *sys.argv[1:]])

try:
    import grpc
    from netsim import frontend_pb2, frontend_pb2_grpc, model_pb2
    from netsim import common_pb2
    from google.protobuf import empty_pb2
except ImportError as exc:  # pragma: no cover - setup guidance, not logic
    sys.exit(
        f"missing generated stubs or grpcio ({exc}).\n"
        f"run: {HERE}/setup.sh"
    )


# --- finding the daemon -------------------------------------------------------

def discover_port() -> int:
    """Locate the netsimd frontend gRPC port.

    Three sources, in order of how much they can be trusted: an explicit
    environment variable, the ini netsimd writes when the emulator starts it, and
    -- last resort, because it depends on the host's `ss` -- whatever netsimd is
    listening on right now.
    """
    env = os.environ.get("NETSIM_GRPC_PORT")
    if env:
        return int(env)

    tmp = os.environ.get("TMPDIR") or "/tmp"
    user = os.environ.get("USER", "")
    for ini in Path(f"{tmp}/android-{user}").rglob("netsim.ini"):
        parser = configparser.ConfigParser()
        # netsim.ini is bare key=value with no section header.
        parser.read_string("[netsim]\n" + ini.read_text())
        port = parser["netsim"].get("grpc.port")
        if port:
            return int(port)

    out = subprocess.run(
        ["ss", "-ltnp"], capture_output=True, text=True, check=False
    ).stdout
    ports = set()
    for line in out.splitlines():
        if "netsimd" not in line:
            continue
        local = line.split()[3]
        port = int(local.rsplit(":", 1)[1])
        if port != 6402:  # the HCI socket, not the frontend
            ports.add(port)
    if len(ports) == 1:
        return ports.pop()
    if not ports:
        sys.exit("no netsimd found - start an emulator first, or set NETSIM_GRPC_PORT")
    sys.exit(f"several netsimd frontends listening ({sorted(ports)}); set NETSIM_GRPC_PORT")


# Set by stub(), so guard() can name the port it failed against.
PORT = 0

STRIPPED_DAEMON = """\
netsimd on localhost:{port} answered UNIMPLEMENTED for FrontendService.

That daemon is the stripped build shipped inside the Android SDK: it serves the
emulators (netsim.packet.PacketStreamer) but has the control plane compiled out
-- `no_cli_ui` and `no_web_ui` are both hardcoded on, and the `netsim` CLI binary
is not in the package. Standalone, `--dev`, and emulator-spawned daemons all
behave this way, so there is nothing to configure here.

Positions need a netsimd built from AOSP (platform/tools/netsim). Until then:
  adb emu geo fix <lon> <lat>                  real GPS, per phone
  emulator -netsim-args "--rssi=ble:-90"       signal strength, set at launch
"""


def guard(call, *args):
    """Run one frontend RPC, turning the SDK daemon's UNIMPLEMENTED into advice.

    Every call here hits the same wall on an SDK netsimd, and a raw grpc
    traceback says nothing about why. See STRIPPED_DAEMON.
    """
    try:
        return call(*args)
    except grpc.RpcError as exc:
        if exc.code() is grpc.StatusCode.UNIMPLEMENTED:
            sys.exit(STRIPPED_DAEMON.format(port=PORT))
        sys.exit(f"netsim rpc failed: {exc.code().name}")


def stub(port: int):
    global PORT
    PORT = port
    channel = grpc.insecure_channel(f"localhost:{port}")
    try:
        grpc.channel_ready_future(channel).result(timeout=5)
    except grpc.FutureTimeoutError:
        sys.exit(f"netsimd on localhost:{port} did not answer")
    return frontend_pb2_grpc.FrontendServiceStub(channel)


# --- operations ---------------------------------------------------------------

def devices(fe):
    return guard(fe.ListDevice, empty_pb2.Empty()).devices


def resolve(fe, name: str):
    """Accept an exact netsim device name or an unambiguous substring."""
    found = [d for d in devices(fe) if d.name == name]
    if not found:
        found = [d for d in devices(fe) if name in d.name]
    if not found:
        known = ", ".join(d.name for d in devices(fe)) or "none"
        sys.exit(f"no netsim device matching {name!r} (present: {known})")
    if len(found) > 1:
        sys.exit(f"{name!r} matches {[d.name for d in found]} - be specific")
    return found[0]


def place(fe, name: str, x: float, y: float, z: float = 0.0) -> None:
    device = resolve(fe, name)
    guard(
        fe.PatchDevice,
        frontend_pb2.PatchDeviceRequest(
            id=device.id,
            device=frontend_pb2.PatchDeviceRequest.PatchDeviceFields(
                position=model_pb2.Position(x=x, y=y, z=z),
            ),
        ),
    )


def walk(fe, name: str, start, end, seconds: float, step: float = 1.0) -> None:
    """Move a device along a straight line, so a link degrades instead of blinking off.

    A phone carried out of a building does not teleport, and the interesting mesh
    behaviour -- store-and-forward holding a frame, a relay taking over a route --
    happens *during* the walk, not at either end of it.
    """
    steps = max(1, int(seconds / step))
    (x0, y0), (x1, y1) = start, end
    for i in range(steps + 1):
        t = i / steps
        x, y = x0 + (x1 - x0) * t, y0 + (y1 - y0) * t
        place(fe, name, x, y)
        print(f"  t+{i * step:5.1f}s  {name}  ({x:7.2f}, {y:7.2f})", flush=True)
        if i != steps:
            time.sleep(step)


def run_scenario(fe, path: Path, metres_per_unit: float) -> None:
    """Replay a timeline of placements and walks.

    Format (see scenarios/collapse.json):

        {"name": "...", "steps": [
          {"at": 0,  "place": {"device": "emulator-5554", "x": 0, "y": 0}},
          {"at": 30, "walk":  {"device": "emulator-5556", "to": [120, 0], "seconds": 20}}
        ]}

    `at` is seconds from the start of the run. Steps run in order; a `walk`
    occupies the clock for its whole duration, which is what you want when the
    point of the run is to watch a route change while it happens.
    """
    spec = json.loads(path.read_text())
    print(f"scenario {spec.get('name', path.stem)}  ({metres_per_unit} m per scene unit)")
    started = time.monotonic()
    for step in spec["steps"]:
        due = float(step.get("at", 0))
        wait = due - (time.monotonic() - started)
        if wait > 0:
            time.sleep(wait)
        if "place" in step:
            p = step["place"]
            place(fe, p["device"], float(p["x"]), float(p["y"]), float(p.get("z", 0)))
            print(f"t+{due:5.1f}s  place {p['device']} ({p['x']}, {p['y']})", flush=True)
        elif "walk" in step:
            w = step["walk"]
            device = resolve(fe, w["device"])
            here = (device.position.x, device.position.y)
            print(f"t+{due:5.1f}s  walk  {w['device']} {here} -> {tuple(w['to'])}", flush=True)
            walk(fe, w["device"], here, tuple(w["to"]), float(w.get("seconds", 10)))
        else:
            sys.exit(f"scenario step has neither 'place' nor 'walk': {step}")
    print("scenario done")


def show(fe) -> None:
    found = devices(fe)
    if not found:
        print("netsim has no devices - is an emulator running?")
        return
    for d in found:
        radios = ", ".join(common_pb2.ChipKind.Name(c.kind) for c in d.chips)
        print(
            f"{d.name:24s} id={d.id:<4d} "
            f"({d.position.x:7.2f}, {d.position.y:7.2f}, {d.position.z:7.2f})  [{radios}]"
        )


# --- entry point --------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--port", type=int, help="netsimd frontend gRPC port")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="show every device netsim knows and where it is")
    sub.add_parser("reset", help="reset all devices to netsim defaults")

    p = sub.add_parser("place", help="put a device at a coordinate")
    p.add_argument("device")
    p.add_argument("x", type=float)
    p.add_argument("y", type=float)
    p.add_argument("z", type=float, nargs="?", default=0.0)

    w = sub.add_parser("walk", help="move a device along a line over time")
    w.add_argument("device")
    w.add_argument("x", type=float)
    w.add_argument("y", type=float)
    w.add_argument("--to", nargs=2, type=float, required=True, metavar=("X", "Y"))
    w.add_argument("--seconds", type=float, default=10.0)

    s = sub.add_parser("scenario", help="replay a timeline of placements and walks")
    s.add_argument("path", type=Path)
    s.add_argument("--metres-per-unit", type=float, default=1.0)

    args = ap.parse_args()
    fe = stub(args.port or discover_port())

    if args.cmd == "list":
        show(fe)
    elif args.cmd == "reset":
        guard(fe.Reset, empty_pb2.Empty())
        print("netsim reset")
    elif args.cmd == "place":
        place(fe, args.device, args.x, args.y, args.z)
        print(f"{args.device} at ({args.x}, {args.y}, {args.z})")
    elif args.cmd == "walk":
        walk(fe, args.device, (args.x, args.y), tuple(args.to), args.seconds)
    elif args.cmd == "scenario":
        run_scenario(fe, args.path, args.metres_per_unit)


if __name__ == "__main__":
    main()
